# This is a basic workflow that is manually triggered

name: Lable Pull Request

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
  
permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  checks: write
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  #label:
    # The type of runner that the job will run on
    #runs-on: self-hosted
    #steps:
    #  - uses: actions/checkout@v2
    #  - uses: actions-ecosystem/action-add-labels@v1.1.0
    #    with:
    #      github_token: ${{secrets.GITHUB_TOKEN}}
    #      labels: bug
          
  Add_label:
    runs-on: self-hosted
    name: self-hosted
    steps:
      - name: Add label
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: bug
          type: add
